export interface Country {
    code: string;
    flag: string;
    name: {
        en: string;
        bg: string;
    };
}

export const COUNTRIES: Country[] = [
    { code: 'AD', flag: '🇦🇩', name: { en: 'Andorra', bg: 'Андора' } },
    { code: 'AE', flag: '🇦🇪', name: { en: 'United Arab Emirates', bg: 'Обединени арабски емирства' } },
    { code: 'AF', flag: '🇦🇫', name: { en: 'Afghanistan', bg: 'Афганистан' } },
    { code: 'AG', flag: '🇦🇬', name: { en: 'Antigua and Barbuda', bg: 'Антигуа и Барбуда' } },
    { code: 'AI', flag: '🇦🇮', name: { en: 'Anguilla', bg: 'Ангуила' } },
    { code: 'AL', flag: '🇦🇱', name: { en: 'Albania', bg: 'Албания' } },
    { code: 'AM', flag: '🇦🇲', name: { en: 'Armenia', bg: 'Армения' } },
    { code: 'AO', flag: '🇦🇴', name: { en: 'Angola', bg: 'Ангола' } },
    { code: 'AQ', flag: '🇦🇶', name: { en: 'Antarctica', bg: 'Антарктида' } },
    { code: 'AR', flag: '🇦🇷', name: { en: 'Argentina', bg: 'Аржентина' } },
    { code: 'AS', flag: '🇦🇸', name: { en: 'American Samoa', bg: 'Американска Самоа' } },
    { code: 'AT', flag: '🇦🇹', name: { en: 'Austria', bg: 'Австрия' } },
    { code: 'AU', flag: '🇦🇺', name: { en: 'Australia', bg: 'Австралия' } },
    { code: 'AW', flag: '🇦🇼', name: { en: 'Aruba', bg: 'Аруба' } },
    { code: 'AX', flag: '🇦🇽', name: { en: 'Åland Islands', bg: 'Оландски острови' } },
    { code: 'AZ', flag: '🇦🇿', name: { en: 'Azerbaijan', bg: 'Азербайджан' } },
    { code: 'BA', flag: '🇧🇦', name: { en: 'Bosnia and Herzegovina', bg: 'Босна и Херцеговина' } },
    { code: 'BB', flag: '🇧🇧', name: { en: 'Barbados', bg: 'Барбадос' } },
    { code: 'BD', flag: '🇧🇩', name: { en: 'Bangladesh', bg: 'Бангладеш' } },
    { code: 'BE', flag: '🇧🇪', name: { en: 'Belgium', bg: 'Белгия' } },
    { code: 'BF', flag: '🇧🇫', name: { en: 'Burkina Faso', bg: 'Буркина Фасо' } },
    { code: 'BG', flag: '🇧🇬', name: { en: 'Bulgaria', bg: 'България' } },
    { code: 'BH', flag: '🇧🇭', name: { en: 'Bahrain', bg: 'Бахрейн' } },
    { code: 'BI', flag: '🇧🇮', name: { en: 'Burundi', bg: 'Бурунди' } },
    { code: 'BJ', flag: '🇧🇯', name: { en: 'Benin', bg: 'Бенин' } },
    { code: 'BL', flag: '🇧🇱', name: { en: 'Saint Barthélemy', bg: 'Сен Бартелеми' } },
    { code: 'BM', flag: '🇧🇲', name: { en: 'Bermuda', bg: 'Бермуда' } },
    { code: 'BN', flag: '🇧🇳', name: { en: 'Brunei', bg: 'Бруней' } },
    { code: 'BO', flag: '🇧🇴', name: { en: 'Bolivia', bg: 'Боливия' } },
    { code: 'BQ', flag: '🇧🇶', name: { en: 'Caribbean Netherlands', bg: 'Карибска Нидерландия' } },
    { code: 'BR', flag: '🇧🇷', name: { en: 'Brazil', bg: 'Бразилия' } },
    { code: 'BS', flag: '🇧🇸', name: { en: 'Bahamas', bg: 'Бахамски острови' } },
    { code: 'BT', flag: '🇧🇹', name: { en: 'Bhutan', bg: 'Бутан' } },
    { code: 'BV', flag: '🇧🇻', name: { en: 'Bouvet Island', bg: 'Остров Буве' } },
    { code: 'BW', flag: '🇧🇼', name: { en: 'Botswana', bg: 'Ботсвана' } },
    { code: 'BY', flag: '🇧🇾', name: { en: 'Belarus', bg: 'Беларус' } },
    { code: 'BZ', flag: '🇧🇿', name: { en: 'Belize', bg: 'Белиз' } },
    { code: 'CA', flag: '🇨🇦', name: { en: 'Canada', bg: 'Канада' } },
    { code: 'CC', flag: '🇨🇨', name: { en: 'Cocos Islands', bg: 'Кокосови острови' } },
    { code: 'CD', flag: '🇨🇩', name: { en: 'Democratic Republic of the Congo', bg: 'Демократична република Конго' } },
    { code: 'CF', flag: '🇨🇫', name: { en: 'Central African Republic', bg: 'Централноафриканска република' } },
    { code: 'CG', flag: '🇨🇬', name: { en: 'Republic of the Congo', bg: 'Република Конго' } },
    { code: 'CH', flag: '🇨🇭', name: { en: 'Switzerland', bg: 'Швейцария' } },
    { code: 'CI', flag: '🇨🇮', name: { en: 'Côte d\'Ivoire', bg: 'Кот д\'Ивоар' } },
    { code: 'CK', flag: '🇨🇰', name: { en: 'Cook Islands', bg: 'Острови Кук' } },
    { code: 'CL', flag: '🇨🇱', name: { en: 'Chile', bg: 'Чили' } },
    { code: 'CM', flag: '🇨🇲', name: { en: 'Cameroon', bg: 'Камерун' } },
    { code: 'CN', flag: '🇨🇳', name: { en: 'China', bg: 'Китай' } },
    { code: 'CO', flag: '🇨🇴', name: { en: 'Colombia', bg: 'Колумбия' } },
    { code: 'CR', flag: '🇨🇷', name: { en: 'Costa Rica', bg: 'Коста Рика' } },
    { code: 'CU', flag: '🇨🇺', name: { en: 'Cuba', bg: 'Куба' } },
    { code: 'CV', flag: '🇨🇻', name: { en: 'Cape Verde', bg: 'Кабо Верде' } },
    { code: 'CW', flag: '🇨🇼', name: { en: 'Curaçao', bg: 'Кюрасао' } },
    { code: 'CX', flag: '🇨🇽', name: { en: 'Christmas Island', bg: 'Остров Коледа' } },
    { code: 'CY', flag: '🇨🇾', name: { en: 'Cyprus', bg: 'Кипър' } },
    { code: 'CZ', flag: '🇨🇿', name: { en: 'Czech Republic', bg: 'Чехия' } },
    { code: 'DE', flag: '🇩🇪', name: { en: 'Germany', bg: 'Германия' } },
    { code: 'DJ', flag: '🇩🇯', name: { en: 'Djibouti', bg: 'Джибути' } },
    { code: 'DK', flag: '🇩🇰', name: { en: 'Denmark', bg: 'Дания' } },
    { code: 'DM', flag: '🇩🇲', name: { en: 'Dominica', bg: 'Доминика' } },
    { code: 'DO', flag: '🇩🇴', name: { en: 'Dominican Republic', bg: 'Доминиканска република' } },
    { code: 'DZ', flag: '🇩🇿', name: { en: 'Algeria', bg: 'Алжир' } },
    { code: 'EC', flag: '🇪🇨', name: { en: 'Ecuador', bg: 'Еквадор' } },
    { code: 'EE', flag: '🇪🇪', name: { en: 'Estonia', bg: 'Естония' } },
    { code: 'EG', flag: '🇪🇬', name: { en: 'Egypt', bg: 'Египет' } },
    { code: 'EH', flag: '🇪🇭', name: { en: 'Western Sahara', bg: 'Западна Сахара' } },
    { code: 'ER', flag: '🇪🇷', name: { en: 'Eritrea', bg: 'Еритрея' } },
    { code: 'ES', flag: '🇪🇸', name: { en: 'Spain', bg: 'Испания' } },
    { code: 'ET', flag: '🇪🇹', name: { en: 'Ethiopia', bg: 'Етиопия' } },
    { code: 'FI', flag: '🇫🇮', name: { en: 'Finland', bg: 'Финландия' } },
    { code: 'FJ', flag: '🇫🇯', name: { en: 'Fiji', bg: 'Фиджи' } },
    { code: 'FK', flag: '🇫🇰', name: { en: 'Falkland Islands', bg: 'Фолклендски острови' } },
    { code: 'FM', flag: '🇫🇲', name: { en: 'Micronesia', bg: 'Микронезия' } },
    { code: 'FO', flag: '🇫🇴', name: { en: 'Faroe Islands', bg: 'Фарьорски острови' } },
    { code: 'FR', flag: '🇫🇷', name: { en: 'France', bg: 'Франция' } },
    { code: 'GA', flag: '🇬🇦', name: { en: 'Gabon', bg: 'Габон' } },
    { code: 'GB', flag: '🇬🇧', name: { en: 'United Kingdom', bg: 'Великобритания' } },
    { code: 'GD', flag: '🇬🇩', name: { en: 'Grenada', bg: 'Гренада' } },
    { code: 'GE', flag: '🇬🇪', name: { en: 'Georgia', bg: 'Грузия' } },
    { code: 'GF', flag: '🇬🇫', name: { en: 'French Guiana', bg: 'Френска Гвиана' } },
    { code: 'GG', flag: '🇬🇬', name: { en: 'Guernsey', bg: 'Гърнзи' } },
    { code: 'GH', flag: '🇬🇭', name: { en: 'Ghana', bg: 'Гана' } },
    { code: 'GI', flag: '🇬🇮', name: { en: 'Gibraltar', bg: 'Гибралтар' } },
    { code: 'GL', flag: '🇬🇱', name: { en: 'Greenland', bg: 'Гренландия' } },
    { code: 'GM', flag: '🇬🇲', name: { en: 'Gambia', bg: 'Гамбия' } },
    { code: 'GN', flag: '🇬🇳', name: { en: 'Guinea', bg: 'Гвинея' } },
    { code: 'GP', flag: '🇬🇵', name: { en: 'Guadeloupe', bg: 'Гваделупа' } },
    { code: 'GQ', flag: '🇬🇶', name: { en: 'Equatorial Guinea', bg: 'Екваториална Гвинея' } },
    { code: 'GR', flag: '🇬🇷', name: { en: 'Greece', bg: 'Гърция' } },
    { code: 'GS', flag: '🇬🇸', name: { en: 'South Georgia', bg: 'Южна Джорджия' } },
    { code: 'GT', flag: '🇬🇹', name: { en: 'Guatemala', bg: 'Гватемала' } },
    { code: 'GU', flag: '🇬🇺', name: { en: 'Guam', bg: 'Гуам' } },
    { code: 'GW', flag: '🇬🇼', name: { en: 'Guinea-Bissau', bg: 'Гвинея-Бисау' } },
    { code: 'GY', flag: '🇬🇾', name: { en: 'Guyana', bg: 'Гвиана' } },
    { code: 'HK', flag: '🇭🇰', name: { en: 'Hong Kong', bg: 'Хонг Конг' } },
    { code: 'HM', flag: '🇭🇲', name: { en: 'Heard Island', bg: 'Остров Хърд' } },
    { code: 'HN', flag: '🇭🇳', name: { en: 'Honduras', bg: 'Хондурас' } },
    { code: 'HR', flag: '🇭🇷', name: { en: 'Croatia', bg: 'Хърватия' } },
    { code: 'HT', flag: '🇭🇹', name: { en: 'Haiti', bg: 'Хаити' } },
    { code: 'HU', flag: '🇭🇺', name: { en: 'Hungary', bg: 'Унгария' } },
    { code: 'ID', flag: '🇮🇩', name: { en: 'Indonesia', bg: 'Индонезия' } },
    { code: 'IE', flag: '🇮🇪', name: { en: 'Ireland', bg: 'Ирландия' } },
    { code: 'IL', flag: '🇮🇱', name: { en: 'Israel', bg: 'Израел' } },
    { code: 'IM', flag: '🇮🇲', name: { en: 'Isle of Man', bg: 'Остров Ман' } },
    { code: 'IN', flag: '🇮🇳', name: { en: 'India', bg: 'Индия' } },
    { code: 'IO', flag: '🇮🇴', name: { en: 'British Indian Ocean Territory', bg: 'Британска територия в Индийския океан' } },
    { code: 'IQ', flag: '🇮🇶', name: { en: 'Iraq', bg: 'Ирак' } },
    { code: 'IR', flag: '🇮🇷', name: { en: 'Iran', bg: 'Иран' } },
    { code: 'IS', flag: '🇮🇸', name: { en: 'Iceland', bg: 'Исландия' } },
    { code: 'IT', flag: '🇮🇹', name: { en: 'Italy', bg: 'Италия' } },
    { code: 'JE', flag: '🇯🇪', name: { en: 'Jersey', bg: 'Джърси' } },
    { code: 'JM', flag: '🇯🇲', name: { en: 'Jamaica', bg: 'Ямайка' } },
    { code: 'JO', flag: '🇯🇴', name: { en: 'Jordan', bg: 'Йордания' } },
    { code: 'JP', flag: '🇯🇵', name: { en: 'Japan', bg: 'Япония' } },
    { code: 'KE', flag: '🇰🇪', name: { en: 'Kenya', bg: 'Кения' } },
    { code: 'KG', flag: '🇰🇬', name: { en: 'Kyrgyzstan', bg: 'Киргизстан' } },
    { code: 'KH', flag: '🇰🇭', name: { en: 'Cambodia', bg: 'Камбоджа' } },
    { code: 'KI', flag: '🇰🇮', name: { en: 'Kiribati', bg: 'Кирибати' } },
    { code: 'KM', flag: '🇰🇲', name: { en: 'Comoros', bg: 'Коморски острови' } },
    { code: 'KN', flag: '🇰🇳', name: { en: 'Saint Kitts and Nevis', bg: 'Сейнт Китс и Невис' } },
    { code: 'KP', flag: '🇰🇵', name: { en: 'North Korea', bg: 'Северна Корея' } },
    { code: 'KR', flag: '🇰🇷', name: { en: 'South Korea', bg: 'Южна Корея' } },
    { code: 'KW', flag: '🇰🇼', name: { en: 'Kuwait', bg: 'Кувейт' } },
    { code: 'KY', flag: '🇰🇾', name: { en: 'Cayman Islands', bg: 'Кайманови острови' } },
    { code: 'KZ', flag: '🇰🇿', name: { en: 'Kazakhstan', bg: 'Казахстан' } },
    { code: 'LA', flag: '🇱🇦', name: { en: 'Laos', bg: 'Лаос' } },
    { code: 'LB', flag: '🇱🇧', name: { en: 'Lebanon', bg: 'Ливан' } },
    { code: 'LC', flag: '🇱🇨', name: { en: 'Saint Lucia', bg: 'Сейнт Лусия' } },
    { code: 'LI', flag: '🇱🇮', name: { en: 'Liechtenstein', bg: 'Лихтенщайн' } },
    { code: 'LK', flag: '🇱🇰', name: { en: 'Sri Lanka', bg: 'Шри Ланка' } },
    { code: 'LR', flag: '🇱🇷', name: { en: 'Liberia', bg: 'Либерия' } },
    { code: 'LS', flag: '🇱🇸', name: { en: 'Lesotho', bg: 'Лесото' } },
    { code: 'LT', flag: '🇱🇹', name: { en: 'Lithuania', bg: 'Литва' } },
    { code: 'LU', flag: '🇱🇺', name: { en: 'Luxembourg', bg: 'Люксембург' } },
    { code: 'LV', flag: '🇱🇻', name: { en: 'Latvia', bg: 'Латвия' } },
    { code: 'LY', flag: '🇱🇾', name: { en: 'Libya', bg: 'Либия' } },
    { code: 'MA', flag: '🇲🇦', name: { en: 'Morocco', bg: 'Мароко' } },
    { code: 'MC', flag: '🇲🇨', name: { en: 'Monaco', bg: 'Монако' } },
    { code: 'MD', flag: '🇲🇩', name: { en: 'Moldova', bg: 'Молдова' } },
    { code: 'ME', flag: '🇲🇪', name: { en: 'Montenegro', bg: 'Черна гора' } },
    { code: 'MF', flag: '🇲🇫', name: { en: 'Saint Martin', bg: 'Сен Мартен' } },
    { code: 'MG', flag: '🇲🇬', name: { en: 'Madagascar', bg: 'Мадагаскар' } },
    { code: 'MH', flag: '🇲🇭', name: { en: 'Marshall Islands', bg: 'Маршалови острови' } },
    { code: 'MK', flag: '🇲🇰', name: { en: 'North Macedonia', bg: 'Северна Македония' } },
    { code: 'ML', flag: '🇲🇱', name: { en: 'Mali', bg: 'Мали' } },
    { code: 'MM', flag: '🇲🇲', name: { en: 'Myanmar', bg: 'Мианмар' } },
    { code: 'MN', flag: '🇲🇳', name: { en: 'Mongolia', bg: 'Монголия' } },
    { code: 'MO', flag: '🇲🇴', name: { en: 'Macau', bg: 'Макао' } },
    { code: 'MP', flag: '🇲🇵', name: { en: 'Northern Mariana Islands', bg: 'Северни Марианови острови' } },
    { code: 'MQ', flag: '🇲🇶', name: { en: 'Martinique', bg: 'Мартиника' } },
    { code: 'MR', flag: '🇲🇷', name: { en: 'Mauritania', bg: 'Мавритания' } },
    { code: 'MS', flag: '🇲🇸', name: { en: 'Montserrat', bg: 'Монсерат' } },
    { code: 'MT', flag: '🇲🇹', name: { en: 'Malta', bg: 'Малта' } },
    { code: 'MU', flag: '🇲🇺', name: { en: 'Mauritius', bg: 'Мавриций' } },
    { code: 'MV', flag: '🇲🇻', name: { en: 'Maldives', bg: 'Малдиви' } },
    { code: 'MW', flag: '🇲🇼', name: { en: 'Malawi', bg: 'Малави' } },
    { code: 'MX', flag: '🇲🇽', name: { en: 'Mexico', bg: 'Мексико' } },
    { code: 'MY', flag: '🇲🇾', name: { en: 'Malaysia', bg: 'Малайзия' } },
    { code: 'MZ', flag: '🇲🇿', name: { en: 'Mozambique', bg: 'Мозамбик' } },
    { code: 'NA', flag: '🇳🇦', name: { en: 'Namibia', bg: 'Намибия' } },
    { code: 'NC', flag: '🇳🇨', name: { en: 'New Caledonia', bg: 'Нова Каледония' } },
    { code: 'NE', flag: '🇳🇪', name: { en: 'Niger', bg: 'Нигер' } },
    { code: 'NF', flag: '🇳🇫', name: { en: 'Norfolk Island', bg: 'Остров Норфолк' } },
    { code: 'NG', flag: '🇳🇬', name: { en: 'Nigeria', bg: 'Нигерия' } },
    { code: 'NI', flag: '🇳🇮', name: { en: 'Nicaragua', bg: 'Никарагуа' } },
    { code: 'NL', flag: '🇳🇱', name: { en: 'Netherlands', bg: 'Нидерландия' } },
    { code: 'NO', flag: '🇳🇴', name: { en: 'Norway', bg: 'Норвегия' } },
    { code: 'NP', flag: '🇳🇵', name: { en: 'Nepal', bg: 'Непал' } },
    { code: 'NR', flag: '🇳🇷', name: { en: 'Nauru', bg: 'Науру' } },
    { code: 'NU', flag: '🇳🇺', name: { en: 'Niue', bg: 'Ниуе' } },
    { code: 'NZ', flag: '🇳🇿', name: { en: 'New Zealand', bg: 'Нова Зеландия' } },
    { code: 'OM', flag: '🇴🇲', name: { en: 'Oman', bg: 'Оман' } },
    { code: 'PA', flag: '🇵🇦', name: { en: 'Panama', bg: 'Панама' } },
    { code: 'PE', flag: '🇵🇪', name: { en: 'Peru', bg: 'Перу' } },
    { code: 'PF', flag: '🇵🇫', name: { en: 'French Polynesia', bg: 'Френска Полинезия' } },
    { code: 'PG', flag: '🇵🇬', name: { en: 'Papua New Guinea', bg: 'Папуа Нова Гвинея' } },
    { code: 'PH', flag: '🇵🇭', name: { en: 'Philippines', bg: 'Филипини' } },
    { code: 'PK', flag: '🇵🇰', name: { en: 'Pakistan', bg: 'Пакистан' } },
    { code: 'PL', flag: '🇵🇱', name: { en: 'Poland', bg: 'Полша' } },
    { code: 'PM', flag: '🇵🇲', name: { en: 'Saint Pierre and Miquelon', bg: 'Сен Пиер и Микелон' } },
    { code: 'PN', flag: '🇵🇳', name: { en: 'Pitcairn Islands', bg: 'Острови Питкерн' } },
    { code: 'PR', flag: '🇵🇷', name: { en: 'Puerto Rico', bg: 'Пуерто Рико' } },
    { code: 'PS', flag: '🇵🇸', name: { en: 'Palestine', bg: 'Палестина' } },
    { code: 'PT', flag: '🇵🇹', name: { en: 'Portugal', bg: 'Португалия' } },
    { code: 'PW', flag: '🇵🇼', name: { en: 'Palau', bg: 'Палау' } },
    { code: 'PY', flag: '🇵🇾', name: { en: 'Paraguay', bg: 'Парагвай' } },
    { code: 'QA', flag: '🇶🇦', name: { en: 'Qatar', bg: 'Катар' } },
    { code: 'RE', flag: '🇷🇪', name: { en: 'Réunion', bg: 'Реюнион' } },
    { code: 'RO', flag: '🇷🇴', name: { en: 'Romania', bg: 'Румъния' } },
    { code: 'RS', flag: '🇷🇸', name: { en: 'Serbia', bg: 'Сърбия' } },
    { code: 'RU', flag: '🇷🇺', name: { en: 'Russia', bg: 'Русия' } },
    { code: 'RW', flag: '🇷🇼', name: { en: 'Rwanda', bg: 'Руанда' } },
    { code: 'SA', flag: '🇸🇦', name: { en: 'Saudi Arabia', bg: 'Саудитска Арабия' } },
    { code: 'SB', flag: '🇸🇧', name: { en: 'Solomon Islands', bg: 'Соломонови острови' } },
    { code: 'SC', flag: '🇸🇨', name: { en: 'Seychelles', bg: 'Сейшели' } },
    { code: 'SD', flag: '🇸🇩', name: { en: 'Sudan', bg: 'Судан' } },
    { code: 'SE', flag: '🇸🇪', name: { en: 'Sweden', bg: 'Швеция' } },
    { code: 'SG', flag: '🇸🇬', name: { en: 'Singapore', bg: 'Сингапур' } },
    { code: 'SH', flag: '🇸🇭', name: { en: 'Saint Helena', bg: 'Света Елена' } },
    { code: 'SI', flag: '🇸🇮', name: { en: 'Slovenia', bg: 'Словения' } },
    { code: 'SJ', flag: '🇸🇯', name: { en: 'Svalbard and Jan Mayen', bg: 'Свалбард и Ян Майен' } },
    { code: 'SK', flag: '🇸🇰', name: { en: 'Slovakia', bg: 'Словакия' } },
    { code: 'SL', flag: '🇸🇱', name: { en: 'Sierra Leone', bg: 'Сиера Леоне' } },
    { code: 'SM', flag: '🇸🇲', name: { en: 'San Marino', bg: 'Сан Марино' } },
    { code: 'SN', flag: '🇸🇳', name: { en: 'Senegal', bg: 'Сенегал' } },
    { code: 'SO', flag: '🇸🇴', name: { en: 'Somalia', bg: 'Сомалия' } },
    { code: 'SR', flag: '🇸🇷', name: { en: 'Suriname', bg: 'Суринам' } },
    { code: 'SS', flag: '🇸🇸', name: { en: 'South Sudan', bg: 'Южен Судан' } },
    { code: 'ST', flag: '🇸🇹', name: { en: 'São Tomé and Príncipe', bg: 'Сао Томе и Принсипе' } },
    { code: 'SV', flag: '🇸🇻', name: { en: 'El Salvador', bg: 'Ел Салвадор' } },
    { code: 'SX', flag: '🇸🇽', name: { en: 'Sint Maarten', bg: 'Синт Мартен' } },
    { code: 'SY', flag: '🇸🇾', name: { en: 'Syria', bg: 'Сирия' } },
    { code: 'SZ', flag: '🇸🇿', name: { en: 'Eswatini', bg: 'Есватини' } },
    { code: 'TC', flag: '🇹🇨', name: { en: 'Turks and Caicos Islands', bg: 'Търкс и Кайкос' } },
    { code: 'TD', flag: '🇹🇩', name: { en: 'Chad', bg: 'Чад' } },
    { code: 'TF', flag: '🇹🇫', name: { en: 'French Southern Territories', bg: 'Френски южни територии' } },
    { code: 'TG', flag: '🇹🇬', name: { en: 'Togo', bg: 'Того' } },
    { code: 'TH', flag: '🇹🇭', name: { en: 'Thailand', bg: 'Тайланд' } },
    { code: 'TJ', flag: '🇹🇯', name: { en: 'Tajikistan', bg: 'Таджикистан' } },
    { code: 'TK', flag: '🇹🇰', name: { en: 'Tokelau', bg: 'Токелау' } },
    { code: 'TL', flag: '🇹🇱', name: { en: 'Timor-Leste', bg: 'Източен Тимор' } },
    { code: 'TM', flag: '🇹🇲', name: { en: 'Turkmenistan', bg: 'Туркменистан' } },
    { code: 'TN', flag: '🇹🇳', name: { en: 'Tunisia', bg: 'Тунис' } },
    { code: 'TO', flag: '🇹🇴', name: { en: 'Tonga', bg: 'Тонга' } },
    { code: 'TR', flag: '🇹🇷', name: { en: 'Turkey', bg: 'Турция' } },
    { code: 'TT', flag: '🇹🇹', name: { en: 'Trinidad and Tobago', bg: 'Тринидад и Тобаго' } },
    { code: 'TV', flag: '🇹🇻', name: { en: 'Tuvalu', bg: 'Тувалу' } },
    { code: 'TW', flag: '🇹🇼', name: { en: 'Taiwan', bg: 'Тайван' } },
    { code: 'TZ', flag: '🇹🇿', name: { en: 'Tanzania', bg: 'Танзания' } },
    { code: 'UA', flag: '🇺🇦', name: { en: 'Ukraine', bg: 'Украйна' } },
    { code: 'UG', flag: '🇺🇬', name: { en: 'Uganda', bg: 'Уганда' } },
    { code: 'UM', flag: '🇺🇲', name: { en: 'U.S. Outlying Islands', bg: 'Отдалечени острови на САЩ' } },
    { code: 'US', flag: '🇺🇸', name: { en: 'United States', bg: 'Съединени американски щати' } },
    { code: 'UY', flag: '🇺🇾', name: { en: 'Uruguay', bg: 'Уругвай' } },
    { code: 'UZ', flag: '🇺🇿', name: { en: 'Uzbekistan', bg: 'Узбекистан' } },
    { code: 'VA', flag: '🇻🇦', name: { en: 'Vatican City', bg: 'Ватикан' } },
    { code: 'VC', flag: '🇻🇨', name: { en: 'Saint Vincent and the Grenadines', bg: 'Сейнт Винсент и Гренадини' } },
    { code: 'VE', flag: '🇻🇪', name: { en: 'Venezuela', bg: 'Венецуела' } },
    { code: 'VG', flag: '🇻🇬', name: { en: 'British Virgin Islands', bg: 'Британски Вирджински острови' } },
    { code: 'VI', flag: '🇻🇮', name: { en: 'U.S. Virgin Islands', bg: 'Американски Вирджински острови' } },
    { code: 'VN', flag: '🇻🇳', name: { en: 'Vietnam', bg: 'Виетнам' } },
    { code: 'VU', flag: '🇻🇺', name: { en: 'Vanuatu', bg: 'Вануату' } },
    { code: 'WF', flag: '🇼🇫', name: { en: 'Wallis and Futuna', bg: 'Уолис и Футуна' } },
    { code: 'WS', flag: '🇼🇸', name: { en: 'Samoa', bg: 'Самоа' } },
    { code: 'XK', flag: '🇽🇰', name: { en: 'Kosovo', bg: 'Косово' } },
    { code: 'YE', flag: '🇾🇪', name: { en: 'Yemen', bg: 'Йемен' } },
    { code: 'YT', flag: '🇾🇹', name: { en: 'Mayotte', bg: 'Майот' } },
    { code: 'ZA', flag: '🇿🇦', name: { en: 'South Africa', bg: 'Южна Африка' } },
    { code: 'ZM', flag: '🇿🇲', name: { en: 'Zambia', bg: 'Замбия' } },
    { code: 'ZW', flag: '🇿🇼', name: { en: 'Zimbabwe', bg: 'Зимбабве' } },
];

// Popular countries that should appear at the top of the list
export const POPULAR_COUNTRIES = [
    'BG', 'DE', 'FR', 'GB', 'IT', 'ES', 'US', 'CA', 'AU', 'NL', 
    'AT', 'CH', 'SE', 'NO', 'DK', 'FI', 'PL', 'CZ', 'GR', 'RO'
];

export const getCountryByCode = (code: string): Country | undefined => {
    return COUNTRIES.find(country => country.code === code);
};

export const getCountriesSorted = (language: 'en' | 'bg' = 'en'): Country[] => {
    const popular = COUNTRIES.filter(country => POPULAR_COUNTRIES.includes(country.code));
    const others = COUNTRIES.filter(country => !POPULAR_COUNTRIES.includes(country.code));
    
    const sortedPopular = popular.sort((a, b) => a.name[language].localeCompare(b.name[language]));
    const sortedOthers = others.sort((a, b) => a.name[language].localeCompare(b.name[language]));
    
    return [...sortedPopular, ...sortedOthers];
}; 